<font color='darkorange'> Unless otherwise noted, **this notebook will not be reviewed or autograded.**</font> You are welcome to use it for scratchwork, but **only the files listed in the exercises will be checked.**

---

# Exercises

For these exercises, add your functions to the *apputil\.py* file and *app\.py* file as instructed. *These exercises use the same [Titanic dataset](https://www.kaggle.com/competitions/titanic/data) as the lab.*


## Exercise 1: Survival Patterns

For this exercise you will analyze survival patterns on the Titanic by looking at passenger class, sex, and age group. Name the function `survival_demographics()`.

1. Create a new column in the Titanic dataset that classifies passengers into age categories (i.e., a pandas `category` series). The categories should be:
    - Child (up to 12)
    - Teen (13–19)
    - Adult (20–59)
    - Senior (60+)  
  
	Hint: The `pd.cut()` function might come in handy here.

2. Group the passengers by class, sex, and age group.  

3. For each group, calculate:  
    - The total number of passengers, `n_passengers`
    - The number of survivors, `n_survivors`
    - The survival rate, `survival_rate`

4. Return a table that includes the results for *all* combinations of class, sex, and age group.  

5. Order the results so they are easy to interpret.  

6. Come up with a clear question that your results table makes you curious about (e.g., “Did women in first class have a higher survival rate than men in other classes?”). Write this question in your `app.py` file above the call to your visualization function, using `st.write("Your Question Here")`.
   
7. Create a Plotly visualization in a function named `visualize_demographic()` that directly addresses your question by returning a Plotly figure (e.g., `fig = px. ...`). You are free to choose the chart type that you think best communicates the findings. Be creative — try different approaches, compare them, and ensure that your chart clearly answers the question you posed.

In [ ]:
import pandas as pd

# Read in titanic dataset
df = pd.read_csv('https://raw.githubusercontent.com/leontoddjohnson/datasets/main/data/titanic.csv')

# Use pd.cut to create age groups based on the Age column
df['Age_Group'] = pd.cut(df["Age"], bins = [0, 12, 19, 59, 60, float("inf")], labels = ["child", "teen", "adult", "senior"])

In [27]:
# Group the passangers by class, sex, and group
df_grouped = df.groupby(['Pclass', 'Sex', 'Age_Group']).agg(
    Survived_Count=('Survived','sum'),
    Passenger_Count=('PassengerId', 'count')
).reset_index()

# Calculate survival percentage
df_grouped['Survival_Percentage'] = ((df_grouped['Survived_Count'] / df_grouped['Passenger_Count']) * 100).round(2)

C:\Users\chris\AppData\Local\Temp\ipykernel_33800\1884866838.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df_grouped = df.groupby(['Pclass', 'Sex', 'Age_Group']).agg(

In [1]:
from apputil import *

df = survival_demographics()

df

c:\Users\chris\OneDrive - Indiana University\Graduate School\MIS\INFO-H 501\Projects\week-5\apputil.py:14: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df_grouped = df.groupby(['Pclass', 'Sex', 'Age_Group']).agg(

,Pclass,Sex,Age_Group,Survived_Count,Passenger_Count,Survival_Percentage
1,1,female,teen,13,13,100.00
4,1,male,child,3,3,100.00
3,1,female,senior,3,3,100.00
19,3,female,senior,1,1,100.00
12,2,male,child,9,9,100.00
9,2,female,teen,8,8,100.00
8,2,female,child,8,8,100.00
2,1,female,adult,66,68,97.06
10,2,female,adult,52,58,89.66
17,3,female,teen,13,22,59.09
16,3,female,child,11,23,47.83
6,1,male,adult,34,80,42.50
18,3,female,adult,22,56,39.29
20,3,male,child,9,25,36.00
5,1,male,teen,1,4,25.00
15,2,male,senior,1,4,25.00
7,1,male,senior,2,14,14.29
22,3,male,adult,26,186,13.98
13,2,male,teen,1,10,10.00
21,3,male,teen,3,38,7.89
14,2,male,adult,4,76,5.26
0,1,female,child,0,1,0.00
23,3,male,senior,0,4,0.00
11,2,female,senior,0,0,NaN

In [30]:
import streamlit as st
import plotly.express as px

# Use the grouped dataframe for analysis
df = survival_demographics()

# Create the two categories for visualization analysis.
df['Category'] = "Other"
df.loc[(df['Pclass'] == 1) & (df['Sex'] == 'male') & (df['Age_Group'] != 'child'), 'Category'] = '1st Class Male'
df.loc[(df['Pclass'] == 3) & (df['Age_Group'] == 'child'), 'Category'] = '3rd Class Child'
df.loc[(df['Pclass'] == 3) & (df['Sex'] == 'male') & (df['Age_Group'] != 'child'), 'Category'] = '3rd Class Male'

# Filter the Dataframe for the visualization
df_viz = df[df['Category'] != "Other"]

# Group by Category and Get Summative Numbers
df_viz = df_viz.groupby('Category', as_index = False).agg({
    'Survived_Count' : "sum",
    'Passenger_Count' : "sum"
})

# Calculate Survival Rate
df_viz["Survival Percentage"] = round((df_viz["Survived_Count"]/df_viz["Passenger_Count"] * 100), 2)

c:\Users\chris\OneDrive - Indiana University\Graduate School\MIS\INFO-H 501\Projects\week-5\apputil.py:14: FutureWarning:

The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

In [36]:
fig = px.bar(
            df_viz,  
            title='Was surviving the Titanic Fair?',
            subtitle='Comparing survival rates for 1st class men, 3rd class children, and 3rd class men.',
             x='Category',
             y='Survival Percentage',
             text='Survival Percentage',
             hover_data={
                'Category': True,
                'Survived_Count': True,
                'Passenger_Count': True,
                'Survival Percentage': ":.1f"
            },
             template='simple_white',
             color_discrete_sequence=px.colors.qualitative.D3
            )
fig.show()

In [28]:
import streamlit as st

from apputil import *

st.write(
'''
# Did men in the first class have a higher survival rate than children in the third class?

'''
)
# Generate and display the figure
fig1 = visualize_demographic()
st.plotly_chart(fig1, use_container_width=True)

2026-06-10 23:34:25.595 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-10 23:34:25.726
  Warning: to view this Streamlit app on a browser, run it with the following
  command:

    streamlit run c:\Users\chris\miniconda3\envs\week-5\Lib\site-packages\ipykernel_launcher.py [ARGUMENTS]
2026-06-10 23:34:25.726 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-10 23:34:25.728 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

KeyError: 'Age_Group'

## Exercise 2: Family Size and Wealth

Using the Titanic dataset, write a function named `family_groups()` to explore the relationship between family size, passenger class, and ticket fare.  

1. Create a new column in the Titanic dataset that represents the total family size for each passenger, `family_size`. Family size is defined as the number of siblings/spouses aboard plus the number of parents/children aboard, plus the passenger themselves.

2. Group the passengers by family size and passenger class. For each group, calculate:  
   - The total number of passengers, `n_passengers`
   - The average ticket fare, `avg_fare`
   - The minimum and maximum ticket fares (to capture variation in wealth), `min_fare` and `max_fare`

3. Return a table with these results, sorted so that the values are clear and easy to interpret (for example, by class and then family size).

4. Write a function called `last_names()` that extracts the last name of each passenger from the `Name` column, and returns the count for each last name (i.e., a pandas series with last name as index, and count as value). Does this result agree with that of the data table above? Share your findings in your app using `st.write`.

5. Just like you did in Exercise 1, come up with a clear question that your results makes you curious about. Write this question in your app.py file above the call to your visualization function. Then, create a Plotly visualization in a function named `visualize_families()` that directly addresses your question. As in Exercise 1 you are free to choose the chart type that you think best communicates the findings.

In [37]:
# Read in titanic dataset
df = pd.read_csv('https://raw.githubusercontent.com/leontoddjohnson/datasets/main/data/titanic.csv')

df['family_size'] = df['SibSp'] + df['Parch'] + 1
df['Count'] = 1

df_histo = df.copy()

df_grouped = df.groupby(['Pclass','family_size']).agg(
    n_passengers=('Count', 'sum'),
    avg_fare=('Fare', 'mean'),
    min_fare=('Fare', 'min'),
    max_fare=('Fare', 'max')
).reset_index()

df_grouped

    Pclass  family_size  n_passengers    avg_fare  min_fare  max_fare
0        1            1           109   63.672514    0.0000  512.3292
1        1            2            70   91.848039   29.7000  512.3292
2        1            3            24   95.681075   26.2833  211.5000
3        1            4             7  133.521429  120.0000  151.5500
4        1            5             2  262.375000  262.3750  262.3750
5        1            6             4  263.000000  263.0000  263.0000
6        2            1           104   14.066106    0.0000   73.5000
7        2            2            34   24.682962   11.5000   33.0000
8        2            3            31   31.693819   13.0000   73.5000
9        2            4            13   36.575969   11.5000   65.0000
10       2            5             1   23.000000   23.0000   23.0000
11       2            6             1   18.750000   18.7500   18.7500
12       3            1           324    9.272052    0.0000   56.4958
13       3            2            57   13.410023    6.4958   24.1500
14       3            3            47   16.378277    7.2292   24.1500
15       3            4             9   20.103689   15.8500   23.4500
16       3            5            12   26.972233   21.0750   34.3750
17       3            6            17   32.420588   27.9000   39.6875
18       3            7            12   29.366667    7.9250   31.3875
19       3            8             6   46.900000   46.9000   46.9000
20       3           11             7   69.550000   69.5500   69.5500

In [3]:
from apputil import *

df = last_names()
df

last_name
Abbing           1
Abbott           2
Abelson          2
Adahl            1
Adams            1
                ..
de Mulder        1
de Pelsmaeker    1
del Carlo        1
van Billiard     1
van Melkebeke    1
Name: Count, Length: 667, dtype: int64

In [38]:
fig = px.histogram(df_histo, 
                   x = 'family_size',
                   template='plotly_white',
                   color_discrete_sequence=px.colors.qualitative.D3
                  )

fig.update_layout(
    bargap=0.1, # gap between bars of adjacent location coordinates
)

fig.show()

In [15]:
df = pd.read_csv('https://raw.githubusercontent.com/leontoddjohnson/datasets/main/data/titanic.csv')

df['last_name'] = df['Name'].apply(lambda x: x.split(',')[0].strip())
df['Count'] = 1

df_groupby = df.groupby('last_name').agg(total_count=('Count', 'sum'))

df_groupby

               total_count
last_name
Abbing                   1
Abbott                   2
Abelson                  2
Adahl                    1
Adams                    1
...                    ...
de Mulder                1
de Pelsmaeker            1
del Carlo                1
van Billiard             1
van Melkebeke            1

[667 rows x 1 columns]

In [21]:
fig = px.histogram(df_groupby, 
                   x='total_count', 
                   template='plotly_white',
                   color_discrete_sequence=px.colors.qualitative.D3
                  )

fig.update_layout(
    bargap=0.1, # gap between bars of adjacent location coordinates
)

fig.show()

In [9]:
# Read in titanic datasets
df = pd.read_csv('https://raw.githubusercontent.com/leontoddjohnson/datasets/main/data/titanic.csv')

# Create a last name column
df["last_name"] = df["Name"].apply(lambda x: x.split(",")[0].strip())

# Group passengers by last name and compute total count
last_names = df["last_name"].value_counts()

last_names

last_name
Andersson          9
Sage               7
Skoog              6
Panula             6
Carter             6
                  ..
Najib              1
Vander Cruyssen    1
Balkic             1
van Melkebeke      1
Bystrom            1
Name: count, Length: 667, dtype: int64

In [25]:
from apputil import *

df_viz_family_size = family_size()

# Adjust family size data frame
df_viz_family_size['group'] = 'family_calc'
df_viz_family_size = df_viz_family_size[['group', 'family_size']]
df_viz_family_size = df_viz_family_size.groupby(["group", "family_size"], as_index=False).size().rename(columns={"size": "count"})
df_viz_family_size

         group  family_size  count
0  family_calc            1    537
1  family_calc            2    161
2  family_calc            3    102
3  family_calc            4     29
4  family_calc            5     15
5  family_calc            6     22
6  family_calc            7     12
7  family_calc            8      6
8  family_calc           11      7

In [16]:
from apputil import *

 # Get the Dataframe(s)
df_viz_last_names = last_names()
df_viz_family_size = family_size()

# Adjust last name data frame
df_viz_last_names = df_viz_last_names.reset_index()
df_viz_last_names.columns = ["last_name", "family_size"]
df_viz_last_names['group'] = 'Last_Names'
df_viz_last_names = df_viz_last_names.groupby(["group", "family_size"], as_index=False).size().rename(columns={"size": "count"})

df_viz_last_names

        group  family_size  count
0  Last_Names            1    534
1  Last_Names            2     83
2  Last_Names            3     28
3  Last_Names            4     14
4  Last_Names            5      1
5  Last_Names            6      5
6  Last_Names            7      1
7  Last_Names            9      1

In [61]:
from apputil import *

df = family_size()

# Reduce Dataframe to needed columns
df = df[['family_size','Survived']] \
    .groupby('family_size') \
    .agg(
        survivors=('Survived','sum'), 
        passengers=('Survived','size')
    ) \
    .reset_index()

df['nonsurvivors'] = df['passengers'] - df['survivors']
df['survival_percentage'] = round(df['survivors'] / df['passengers'] * 100,2)

df = family_size()
df = df[['family_size','Survived']].groupby(['family_size', 'Survived']).value_counts().reset_index()
df['percentage'] = round(df['count'] / df.groupby('family_size')['count'].transform('sum') * 100,2)
df['Survived'] = df['Survived'].map({
    0: 'dead',
    1: 'alive'
})

fig = px.bar(
    df,
    x = 'family_size',
    y = 'percentage',
    color = 'Survived',
    barmode = 'stack',
    text='percentage',
    template='simple_white',
    title='Percentage of Titanic Passengers that survived by Family Size',
    color_discrete_map={
        'dead': 'gray',
        'alive': 'blue'
    },
    category_orders={
        'Survived':['alive','dead']
    },
    hover_data = {
        'family_size': True,
        'count': True,
        'percentage': True,
        'Survived': True
    },
    labels={
        'family_size' : 'Family Size',
        'percentage' : 'Percent of Passengers'
    }
)

fig

## Bonus Question

Add a new column, `older_passenger`, to the Titanic dataset that indicates whether each passenger’s age is above the median age for *their* passenger class. So, suppose row $x$ is in passenger class 2. Then, a value of `True` at row $x$ would indicate that passenger older than 50% of class 2 passengers, and `False` would indicate that they younger.

- You should use pandas functions to accomplish this.
- The new column should contain Boolean values (True if the age is above the median, False if less than or equal to).
- Return the updated table in the function `determine_age_division()`

Once you’ve created this column, consider how this age division relates to your analysis above. Try to visualize this analysis in Plotly using the function name `visualize_age_division()`.

In [82]:
df = pd.read_csv('https://raw.githubusercontent.com/leontoddjohnson/datasets/main/data/titanic.csv')

df['older_passenger'] = df['Age'] > df.groupby('Pclass')['Age'].transform('median')

df = df[['older_passenger', 'Survived']]

prob_matrix = pd.crosstab(
    index=df['older_passenger'],
    columns=df['Survived'],
    normalize='index'
) * 100

prob_matrix = prob_matrix.round(1)

prob_matrix = prob_matrix.rename(
    index={False: 'Younger', True: 'Older'},
    columns={0: 'Died', 1: 'Survived'}
)

fig = px.imshow(
    prob_matrix,
    text_auto='.1f',
    color_continuous_scale='Blues',
    aspect='auto',
    labels={
        'x': 'Outcome',
        'y': 'Passenger Group',
        'color': 'Percent'
    },
    title='Survival Rate by Passenger Age Group'
)

fig.update_traces(
    texttemplate='%{z:.1f}%',
    hovertemplate='Passenger Group: %{y}<br>Outcome: %{x}<br>Percent: %{z:.1f}%<extra></extra>'
)

fig.update_layout(
    xaxis_title='Outcome',
    yaxis_title='Passenger Group',
    coloraxis_colorbar_title='Percent',
    title_x=0.5
)

fig.show()